mibew_operator_status_has_online_operators:
  path: /opstatus
  defaults:
    _controller: Mibew\Mibew\Plugin\OperatorStatus\Controller\OperatorStatusController::hasOnlineOperatorsAction

mibew_operator_status_is_operator_online:
  path: /opstatus/{opcode}
  defaults:
    _controller: Mibew\Mibew\Plugin\OperatorStatus\Controller\OperatorStatusController::isOperatorOnlineAction
